# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json
name: tdd-azure-ai-foundry-private
metadata:
  template: tdd-Azure-AI-Foundry-hub-and-project@1.0.0

infra:
  provider: bicep
  path: infra
  module: main

pipeline:
  provider: github
  
hooks:
  postprovision:
    windows:
      shell: pwsh
      run: |
        $scriptPath = "$(Get-Location)\scripts\postprovision.ps1"
        if (Test-Path $scriptPath) {
          & $scriptPath
        } else {
          Write-Host "Script not found: $scriptPath"
          exit 1
        }
    posix:
      shell: sh
      run: |
        chmod +x ./scripts/postprovision.sh || echo "chmod failed, running anyway..."
        ./scripts/postprovision.sh
      interactive: true
      continueOnError: false
