# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json
name: azure-ai-foundry-private
metadata:
  template: azd-Azure-AI-Foundry-hub-and-project@1.0.0

infra:
  provider: bicep
  path: infra
  module: main

pipeline:
  provider: github

hooks:
  postprovision:
    windows:
      shell: pwsh
      run: |
        Write-Host ""
        Write-Host "========================================" -ForegroundColor Cyan
        Write-Host "  Granting Current User Permissions..." -ForegroundColor Cyan
        Write-Host "========================================" -ForegroundColor Cyan
        
        # Get current user's Object ID
        $userId = az ad signed-in-user show --query id -o tsv
        Write-Host "User Object ID: $userId" -ForegroundColor Gray
        
        # Grant Cognitive Services Contributor (for Content Understanding)
        Write-Host "Granting Cognitive Services Contributor role..." -ForegroundColor Yellow
        az role assignment create --assignee $userId --role "Cognitive Services Contributor" --scope "/subscriptions/$env:AZURE_SUBSCRIPTION_ID/resourceGroups/$env:AZURE_RESOURCE_GROUP/providers/Microsoft.CognitiveServices/accounts/$env:COGNITIVE_SERVICES_NAME" 2>$null
        
        # Grant Cognitive Services User (for API access)
        Write-Host "Granting Cognitive Services User role..." -ForegroundColor Yellow
        az role assignment create --assignee $userId --role "Cognitive Services User" --scope "/subscriptions/$env:AZURE_SUBSCRIPTION_ID/resourceGroups/$env:AZURE_RESOURCE_GROUP/providers/Microsoft.CognitiveServices/accounts/$env:COGNITIVE_SERVICES_NAME" 2>$null
        
        # Grant Azure AI Developer on AI Hub
        Write-Host "Granting Azure AI Developer role on Hub..." -ForegroundColor Yellow
        az role assignment create --assignee $userId --role "Azure AI Developer" --scope "$env:AI_HUB_ID" 2>$null
        
        # Grant Azure AI Developer on AI Project
        Write-Host "Granting Azure AI Developer role on Project..." -ForegroundColor Yellow
        az role assignment create --assignee $userId --role "Azure AI Developer" --scope "$env:AI_PROJECT_ID" 2>$null
        
        Write-Host ""
        Write-Host "========================================" -ForegroundColor Cyan
        Write-Host "  Azure AI Foundry Deployment Complete" -ForegroundColor Cyan
        Write-Host "========================================" -ForegroundColor Cyan
        Write-Host ""
        Write-Host "Resource Group: $env:AZURE_RESOURCE_GROUP" -ForegroundColor Green
        Write-Host "Location: $env:AZURE_LOCATION" -ForegroundColor Green
        Write-Host ""
        Write-Host "--- Jumpbox VM ---" -ForegroundColor Yellow
        Write-Host "VM Name: $env:VM_NAME"
        Write-Host "Private IP: $env:VM_PRIVATE_IP"
        Write-Host ""
        if ($env:BASTION_ENABLED -eq "true") {
          Write-Host "--- Azure Bastion ---" -ForegroundColor Yellow
          Write-Host "Bastion Name: $env:BASTION_NAME"
          Write-Host "Connect via: Azure Portal > Bastion > Connect"
          Write-Host ""
        }
        Write-Host "--- AI Foundry ---" -ForegroundColor Yellow
        Write-Host "Hub Name: $env:AI_HUB_NAME"
        Write-Host "Project Name: $env:AI_PROJECT_NAME"
        Write-Host "AI Services: $env:COGNITIVE_SERVICES_NAME"
        Write-Host "Portal URL: https://ai.azure.com"
        Write-Host ""
        Write-Host "--- Next Steps ---" -ForegroundColor Magenta
        Write-Host "1. Connect to the Jumpbox VM via Azure Bastion"
        Write-Host "2. From inside the VM, browse to https://ai.azure.com"
        Write-Host "3. Sign in with your Microsoft Entra ID credentials"
        Write-Host "4. All services are private - accessible only from the VNet"
        Write-Host ""
    posix:
      shell: bash
      run: |
        echo ""
        echo "========================================"
        echo "  Granting Current User Permissions..."
        echo "========================================"
        
        # Get current user's Object ID
        userId=$(az ad signed-in-user show --query id -o tsv)
        echo "User Object ID: $userId"
        
        # Grant Cognitive Services Contributor (for Content Understanding)
        echo "Granting Cognitive Services Contributor role..."
        az role assignment create --assignee $userId --role "Cognitive Services Contributor" --scope "/subscriptions/$AZURE_SUBSCRIPTION_ID/resourceGroups/$AZURE_RESOURCE_GROUP/providers/Microsoft.CognitiveServices/accounts/$COGNITIVE_SERVICES_NAME" 2>/dev/null
        
        # Grant Cognitive Services User (for API access)
        echo "Granting Cognitive Services User role..."
        az role assignment create --assignee $userId --role "Cognitive Services User" --scope "/subscriptions/$AZURE_SUBSCRIPTION_ID/resourceGroups/$AZURE_RESOURCE_GROUP/providers/Microsoft.CognitiveServices/accounts/$COGNITIVE_SERVICES_NAME" 2>/dev/null
        
        # Grant Azure AI Developer on AI Hub
        echo "Granting Azure AI Developer role on Hub..."
        az role assignment create --assignee $userId --role "Azure AI Developer" --scope "$AI_HUB_ID" 2>/dev/null
        
        # Grant Azure AI Developer on AI Project
        echo "Granting Azure AI Developer role on Project..."
        az role assignment create --assignee $userId --role "Azure AI Developer" --scope "$AI_PROJECT_ID" 2>/dev/null
        
        echo ""
        echo "========================================"
        echo "  Azure AI Foundry Deployment Complete"
        echo "========================================"
        echo ""
        echo "Resource Group: $AZURE_RESOURCE_GROUP"
        echo "Location: $AZURE_LOCATION"
        echo ""
        echo "--- Jumpbox VM ---"
        echo "VM Name: $VM_NAME"
        echo "Private IP: $VM_PRIVATE_IP"
        echo ""
        if [ "$BASTION_ENABLED" = "true" ]; then
          echo "--- Azure Bastion ---"
          echo "Bastion Name: $BASTION_NAME"
          echo "Connect via: Azure Portal > Bastion > Connect"
          echo ""
        fi
        echo "--- AI Foundry ---"
        echo "Hub Name: $AI_HUB_NAME"
        echo "Project Name: $AI_PROJECT_NAME"
        echo "AI Services: $COGNITIVE_SERVICES_NAME"
        echo "Portal URL: https://ai.azure.com"
        echo ""
        echo "--- Next Steps ---"
        echo "1. Connect to the Jumpbox VM via Azure Bastion"
        echo "2. From inside the VM, browse to https://ai.azure.com"
        echo "3. Sign in with your Microsoft Entra ID credentials"
        echo "4. All services are private - accessible only from the VNet"
        echo ""
